// Generated by scripts/generate-license-keypair.ts — do not hand-edit.
// This is the PUBLIC half of the exe-license signing keypair. It ships inside the compiled exe
// and can only verify license signatures, never create them, so committing it is safe.
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAsvsIRXV2RNkSWReVVGzlitG0M8tSQM8FTm5Vh6sEXJg=
-----END PUBLIC KEY-----`;
