import type { Hono } from "hono";
import type { AppEnv } from "@api/honoTypes";
import { UI_MANIFEST, UI_MANIFEST_AVAILABLE } from "@generated/uiManifest";

const VITE_DEV_SERVER = "http://localhost:5173";

/**
 * Serves the built UI from the manifest generated by scripts/generate-ui-manifest.ts. Every asset
 * was imported there with `{ type: "file" }`, which `bun build --compile` embeds directly into
 * the standalone exe — so `Bun.file(asset.path)` reads from disk during `bun run` and from the
 * embedded blob once compiled, with no branching needed here. Falls back to proxying the Vite dev
 * server only when no UI build has been generated yet (fresh checkout, backend-only dev loop).
 */
export function registerStatic(hono: Hono<AppEnv>) {
  hono.get("*", async (c) => {
    if (c.req.path.startsWith("/api") || c.req.path === "/ws") return c.notFound();

    if (UI_MANIFEST_AVAILABLE) {
      const reqPath = c.req.path === "/" ? "/index.html" : c.req.path;
      const asset = UI_MANIFEST[reqPath] ?? UI_MANIFEST["/index.html"]!; // SPA fallback — index.html is always present when UI_MANIFEST_AVAILABLE
      const headers: Record<string, string> = { "Content-Type": asset.contentType };
      if (asset.immutable) headers["Cache-Control"] = "public, max-age=31536000, immutable";
      return new Response(Bun.file(asset.path), { headers });
    }

    try {
      const upstream = await fetch(VITE_DEV_SERVER + c.req.path + (c.req.query() ? "?" + new URLSearchParams(c.req.query() as Record<string, string>) : ""));
      return new Response(upstream.body, { status: upstream.status, headers: upstream.headers });
    } catch {
      return c.text(
        "Argus UI dev server not reachable at " + VITE_DEV_SERVER + ". Run `bun run dev:ui` alongside the backend, or `bun run build:ui && bun run generate:ui-manifest` to serve a built copy.",
        502
      );
    }
  });
}
