/**
 * Generates src/generated/migrationsManifest.ts, embedding every migrations/*.sql file's content
 * via `import sql from "..." with { type: "text" }`. This is a real bugfix, not polish: the old
 * runtime code read migrations off disk via `readdirSync(migrationsDir)` relative to
 * `import.meta.dir`, which resolves to a real path in `bun run` but to a virtual in-binary path
 * with no matching migrations/ folder once compiled with `bun build --compile` — so a freshly
 * compiled exe silently created zero tables ("no such table: devices" on first API call) because
 * `runMigrations` treated "directory not found" as "nothing to migrate" rather than failing loudly.
 * Embedding the SQL text directly at compile time removes the runtime filesystem dependency
 * entirely, for both `bun run` and the compiled exe.
 */
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const MIGRATIONS_DIR = join(import.meta.dir, "..", "migrations");
const OUT_DIR = join(import.meta.dir, "..", "src", "generated");
const OUT_FILE = join(OUT_DIR, "migrationsManifest.ts");

const files = readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const importLines: string[] = [];
const entryLines: string[] = [];

files.forEach((file, i) => {
  const varName = `migration_${i}`;
  const importPath = relative(OUT_DIR, join(MIGRATIONS_DIR, file)).split(sep).join("/");
  const specifier = importPath.startsWith(".") ? importPath : `./${importPath}`;
  importLines.push(`import ${varName} from "${specifier}" with { type: "text" };`);
  entryLines.push(`  { filename: ${JSON.stringify(file)}, sql: ${varName} },`);
});

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT_FILE,
  `// AUTO-GENERATED by scripts/generate-migrations-manifest.ts — do not edit by hand.\n` +
    `// Regenerate with \`bun run generate:migrations-manifest\` after adding a migrations/*.sql file.\n\n` +
    `${importLines.join("\n")}\n\n` +
    `export interface MigrationFile {\n  filename: string;\n  sql: string;\n}\n\n` +
    `export const MIGRATIONS: MigrationFile[] = [\n${entryLines.join("\n")}\n];\n`
);

// eslint-disable-next-line no-console
console.log(`[generate-migrations-manifest] embedded ${files.length} migration(s) into ${relative(process.cwd(), OUT_FILE)}`);
