#!/usr/bin/env bun
/**
 * One-time setup: generates the Ed25519 keypair that backs exe-mode licensing.
 *
 * The PUBLIC key gets written into src/domain/licensePublicKey.ts and committed — it's safe to
 * ship inside the exe, since it can only verify signatures, not create them.
 *
 * The PRIVATE key gets written to secrets/license-private-key.pem and is NEVER committed
 * (.gitignore excludes secrets/). It's the only thing that can sign a valid license file — keep
 * it somewhere durable (password manager, encrypted backup). If it's lost, every license you've
 * already issued still verifies fine (verification only needs the public key), but you can't
 * issue new ones without generating a new keypair and accepting that old licenses were signed by
 * a now-different key.
 *
 * Re-running this script overwrites both files and invalidates every license signed with the old
 * key — only do that deliberately.
 *
 * Usage: bun run scripts/generate-license-keypair.ts
 */
import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SECRETS_DIR = join(ROOT, "secrets");
const PRIVATE_KEY_PATH = join(SECRETS_DIR, "license-private-key.pem");
const PUBLIC_KEY_MODULE_PATH = join(ROOT, "src", "domain", "licensePublicKey.ts");

if (existsSync(PRIVATE_KEY_PATH)) {
  console.error(
    `A private key already exists at ${PRIVATE_KEY_PATH}.\n` +
      "Re-running this script would invalidate every license already issued with it.\n" +
      "Delete it first if you really mean to rotate the keypair."
  );
  process.exit(1);
}

const { publicKey, privateKey } = generateKeyPairSync("ed25519");

const publicKeyPem = publicKey.export({ type: "spki", format: "pem" }).toString();
const privateKeyPem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();

if (!existsSync(SECRETS_DIR)) mkdirSync(SECRETS_DIR, { recursive: true });
writeFileSync(PRIVATE_KEY_PATH, privateKeyPem, { mode: 0o600 });

const moduleSource = `// Generated by scripts/generate-license-keypair.ts — do not hand-edit.
// This is the PUBLIC half of the exe-license signing keypair. It ships inside the compiled exe
// and can only verify license signatures, never create them, so committing it is safe.
export const LICENSE_PUBLIC_KEY_PEM = \`${publicKeyPem.trim()}\`;
`;
writeFileSync(PUBLIC_KEY_MODULE_PATH, moduleSource);

console.log("Keypair generated.");
console.log(`  Public key  -> ${PUBLIC_KEY_MODULE_PATH} (commit this)`);
console.log(`  Private key -> ${PRIVATE_KEY_PATH} (NEVER commit this — back it up somewhere safe)`);
