#!/usr/bin/env bun
/**
 * One-time setup: generates the Ed25519 keypair that backs signed update feeds.
 *
 * Deliberately a SEPARATE keypair from the license-signing one (scripts/generate-license-keypair.ts)
 * — a compromise of the key that issues customer licenses should never also let an attacker forge
 * a signed update the app will auto-install.
 *
 * The PUBLIC key gets written into src/domain/updateFeedPublicKey.ts and committed — it's safe to
 * ship inside the exe, since it can only verify signatures, not create them.
 *
 * The PRIVATE key gets written to secrets/release-private-key.pem and is NEVER committed
 * (.gitignore excludes secrets/). It's the only thing that can sign a feed the app will accept —
 * keep it somewhere durable. If it's lost, generate a new keypair (old signed feeds still verify
 * against the old public key only, so also update the shipped app to the new one on next release).
 *
 * Re-running this script overwrites both files and invalidates every feed signed with the old key.
 *
 * Usage: bun run scripts/generate-release-keypair.ts
 */
import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SECRETS_DIR = join(ROOT, "secrets");
const PRIVATE_KEY_PATH = join(SECRETS_DIR, "release-private-key.pem");
const PUBLIC_KEY_MODULE_PATH = join(ROOT, "src", "domain", "updateFeedPublicKey.ts");

if (existsSync(PRIVATE_KEY_PATH)) {
  console.error(
    `A private key already exists at ${PRIVATE_KEY_PATH}.\n` +
      "Re-running this script would invalidate every update feed already signed with it.\n" +
      "Delete it first if you really mean to rotate the keypair."
  );
  process.exit(1);
}

const { publicKey, privateKey } = generateKeyPairSync("ed25519");

const publicKeyPem = publicKey.export({ type: "spki", format: "pem" }).toString();
const privateKeyPem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();

if (!existsSync(SECRETS_DIR)) mkdirSync(SECRETS_DIR, { recursive: true });
writeFileSync(PRIVATE_KEY_PATH, privateKeyPem, { mode: 0o600 });

const moduleSource = `// Generated by scripts/generate-release-keypair.ts — do not hand-edit.
// This is the PUBLIC half of the update-feed signing keypair. It ships inside the compiled exe
// and can only verify feed signatures, never create them, so committing it is safe.
export const UPDATE_FEED_PUBLIC_KEY_PEM = \`${publicKeyPem.trim()}\`;
`;
writeFileSync(PUBLIC_KEY_MODULE_PATH, moduleSource);

console.log("Keypair generated.");
console.log(`  Public key  -> ${PUBLIC_KEY_MODULE_PATH} (commit this)`);
console.log(`  Private key -> ${PRIVATE_KEY_PATH} (NEVER commit this — back it up somewhere safe)`);
