/**
 * Walks ui/dist (the built frontend) and generates src/generated/uiManifest.ts, a module that
 * `import`s every built asset with `{ type: "file" }`. That import attribute is what makes
 * `bun build --compile` embed the file's bytes directly into the standalone exe — the resulting
 * string is a real disk path in `bun run` (dev/test) and a transparent handle into the embedded
 * blob once compiled, so `src/api/static.ts` can call `Bun.file()` on it unconditionally in both
 * modes without knowing which one it's running in.
 *
 * Run via `bun run generate:ui-manifest` (chained into `build` and `compile`). If ui/dist doesn't
 * exist (no UI build yet), emits an empty stub so the module still type-checks and the server
 * falls back to proxying the Vite dev server.
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";

const UI_DIST = join(import.meta.dir, "..", "ui", "dist");
const OUT_DIR = join(import.meta.dir, "..", "src", "generated");
const OUT_FILE = join(OUT_DIR, "uiManifest.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
};

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function writeStub(reason: string) {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    OUT_FILE,
    `// AUTO-GENERATED by scripts/generate-ui-manifest.ts — do not edit by hand.\n` +
      `// ${reason}\n\n` +
      `export interface UiAsset {\n  path: string;\n  contentType: string;\n  immutable: boolean;\n}\n\n` +
      `export const UI_MANIFEST: Record<string, UiAsset> = {};\n` +
      `export const UI_MANIFEST_AVAILABLE = false;\n`
  );
  // eslint-disable-next-line no-console
  console.log(`[generate-ui-manifest] ${reason} — wrote empty stub to ${relative(process.cwd(), OUT_FILE)}`);
}

if (!existsSync(join(UI_DIST, "index.html"))) {
  writeStub("ui/dist/index.html not found (run `bun run build:ui` first for a real manifest)");
  process.exit(0);
}

const files = walk(UI_DIST).sort();

// bun-types ships ambient `declare module "*.ext"` for these extensions typed as something other
// than a plain string (e.g. *.html -> HTMLBundle, for Bun's unrelated native HTML-bundling
// feature) — src/generated/file-imports.d.ts covers every other extension as `string`, but these
// need a cast at the import site instead of a redeclaration (which would conflict).
const BUN_TYPES_OWNED_EXTENSIONS = new Set([".html", ".json", ".jsonc", ".json5", ".yaml", ".yml", ".toml", ".txt"]);

const importLines: string[] = [];
const entryLines: string[] = [];

files.forEach((absPath, i) => {
  const routePath = "/" + relative(UI_DIST, absPath).split(sep).join("/");
  const varName = `asset_${i}`;
  // Relative import path from the generated file's own directory (src/generated/) to the dist file.
  const importPath = relative(OUT_DIR, absPath).split(sep).join("/");
  const importSpecifier = importPath.startsWith(".") ? importPath : `./${importPath}`;
  const ext = extname(absPath);
  const rawVarName = BUN_TYPES_OWNED_EXTENSIONS.has(ext) ? `${varName}_raw` : varName;
  importLines.push(`import ${rawVarName} from "${importSpecifier}" with { type: "file" };`);
  if (rawVarName !== varName) importLines.push(`const ${varName} = ${rawVarName} as unknown as string;`);
  const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";
  const immutable = routePath !== "/index.html";
  entryLines.push(
    `  ${JSON.stringify(routePath)}: { path: ${varName}, contentType: ${JSON.stringify(contentType)}, immutable: ${immutable} },`
  );
});

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT_FILE,
  `// AUTO-GENERATED by scripts/generate-ui-manifest.ts — do not edit by hand.\n` +
    `// Regenerate with \`bun run generate:ui-manifest\` after any \`bun run build:ui\`.\n\n` +
    `${importLines.join("\n")}\n\n` +
    `export interface UiAsset {\n  path: string;\n  contentType: string;\n  immutable: boolean;\n}\n\n` +
    `export const UI_MANIFEST: Record<string, UiAsset> = {\n${entryLines.join("\n")}\n};\n\n` +
    `export const UI_MANIFEST_AVAILABLE = true;\n`
);

// eslint-disable-next-line no-console
console.log(`[generate-ui-manifest] embedded ${files.length} file(s) into ${relative(process.cwd(), OUT_FILE)}`);
