import type { NotifyPayload } from "@ports/services";

const SEVERITY_COLOR: Record<string, string> = {
  critical: "#ef4444",
  warning: "#f59e0b",
  info: "#22c55e",
};

// A small (40px) white-background render of the app icon, base64-inlined rather than linked —
// this email describes a device on the customer's own LAN going down, so it has to render
// correctly even when read somewhere that can't reach that LAN's dashboard (or any network at
// all: most mail clients also block remote images by default until the user clicks "show
// images"). Regenerated by scripts/generate-icon.py alongside every other icon asset.
const LOGO_DATA_URI =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAFV0lEQVR4nO2Yy4scVRTGf/dWVT+mp6fzMjEhKJnoiC5igpDEVxDBBEEk6EayigZxI4p/gI+dC0Fwo1kF3bgRxE0EF5IsFF2o+IiJwZjRSWYymZ5HT3e6q6vqPuRWDU4nZJoOKeMs/JqGrup76n51vnPPuecKa61lFUOyyiFZ5ZCscvg3ZT0OTC49xQAPZbfjExCUQRSB7cDIrfZgDHwN6hz8OZXdutJa/vtyAzoJTFwATgPfAuGt8uBZoA4TF6HeBCEV1XkfTywPiSKYnYG5hmZ2xqPqw+2XoViGwhOA+DcIOg/8CK05OH8JYq3xpMAYkAKC0vJQaUEnkEQgrGH2iqVe99iyHrZ+Af4+YChvic+DXoBT4xB2DUYJlAJf+KxdC16yPNT93lBxBC1xDMoItDRMzENnEYyTnpwJtheg1ck8oxUpuTiyDAVw7gyEo8tjSzvh/F9QHfJRicUom9okMUQakkZOErsiI0QWMHPT4IeOmF66ZykVPYyFseevttu0A9bebTnzocC3Ht1Y48qVC4cohO4cFPMg2BvNzcnsSrsVLCzGWEo+qBU0KJQFcQQ6giQBaxxBRXPWTx9Uu44Tbphgr11jBrxyFlcIicWmBMp90odnsnBIuhZX8Z0H63VoLsLWf+YQ+axi5zjbgsQ6cd0HrAftnvx3LRyppJulHetiwUITKHYHnfUGCLqUESUQi0xqJ7EKIFF9XqoDytlEFmtESjJSMFz4FwgWAlhsgXExZ00qV1wA2ycPNJvQDTOCbjW5l7IKyqWcCaqItFK0Q4WUJnWhC26lwF2uBCe/82KSGKzNYk3HmmrJy5dgewbChoulBCnF0mQW0wHRR64wTB2X5j8HF7cqjok6ZaImFEdyInhlBlqLTiqTrbqMX5o++mV6l/N8C3Gs05rgvG60pbWQvXRuBBcnHDlIQkM3Fml1KBYgKUKpT8MwV3fVBLS2GHRKzsSWjoXGBKy7K6dSV/8dGvNw7lQXpQxH3qqSxJaFOnT7ENz3pItbaNQ1M1OKSxci2h1NtwP1PwaZeUCCP38DpWF4+sh6dj9RoT6dcO+eClN/QOGaGOztwfYcgqcOwdlfO2y+Q/LIgTXM1xWXpmH8l5sk2DvR6J3w+LOg/Ll0//f64TMUi3DwMDx84Gq73srwygPZNuyN9zez6/ESid9g/3M1du/LdjuDQAzSdp58Ez77dJofTp1jw/oR0B7DaxIe27sTXVa8eOz6ofz2g9BqwX37Z/n84xka85axXR5bhseolSQvHc9J4g/e+43JyVm2bC0yVLZUaoZ2x/DVCYMor2w3tAk6IXxy9CKe57F5a4Gpcc1PPyzwzfd9auSNrmK/YhBBiBEaY7sIJKUybByWbLh9Zbu4qPAKknVbnOwRLtlURgS+bmOl2+FW8yEopU+oQoRwedA5PS0lhFFIcU2wohBDazSJjYlVdyk2l6qJDvA9ZzfA3IMMCpRPzY5htSTWIYnpkpiYSLUJSs4v10e5FqNNTKKj7GsUyvhUvFG6fTYZAxHsXTuvfrSZoBbie8NU5SjSDKGMRmuJoacZuQZKxQjjExuFZ2rUvO2UZRUzMsNrxwZrlleUuDdd3L+/zNHT24BtvPPCab47HiCoEUYLSG/Tig83WrKoFghMDVEU7DjY5uV3BygfvTz+P936T89mehGC/R6E2+rtdCuEXJCPxPMQnYTpOSgVQASw8RnXIK8SD9Z/h1+/hPFFkAHcVoRH90J1dJUQDJswPQlz7XSfjV+RaZOVB3IhWBmDiTrIGAIp+SuCEXcumANySzOLs5ruJQ/Xrmy4x+IHN3DG1gf/50FuEn8DUQaS78Bpux0AAAAASUVORK5CYII=";

export function emailHtml(payload: NotifyPayload, baseUrl: string): string {
  const { alert, device, affectedDevices } = payload;
  const color = SEVERITY_COLOR[alert.severity] ?? "#64748b";
  const deepLink = `${baseUrl}/devices/${device.id}`;

  // A storm/aggregate notification names every device it covers, in its own list — the single
  // "Device" row below is only ever one representative device, which would otherwise make a
  // 20-device outage look like it's about one box.
  const isStorm = affectedDevices && affectedDevices.length > 0;
  const deviceListHtml = isStorm
    ? `<div style="margin:0 0 18px;">
          <div style="color:#94a3b8;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;">Affected devices (${affectedDevices.length})</div>
          <ul style="margin:0;padding-left:18px;color:#334155;font-size:13px;line-height:22px;">
            ${affectedDevices.map((d) => `<li>${escapeHtml(d.name)} <span style="color:#94a3b8;">(${escapeHtml(d.ip)})</span></li>`).join("")}
          </ul>
        </div>`
    : alert.detail
      ? `<p style="font-size:14px;line-height:22px;color:#3f3f46;margin:0 0 18px;">${escapeHtml(alert.detail)}</p>`
      : "";

  const detailRows = isStorm
    ? ""
    : row("Device", escapeHtml(device.name)) + row("IP", escapeHtml(device.ip)) + row("Type", escapeHtml(device.type));

  const ackButton = payload.ackUrl
    ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:22px;">
        <tr><td bgcolor="#7c3aed" style="background-color:#7c3aed;border-radius:9999px;">
          <a href="${payload.ackUrl}" style="display:inline-block;padding:11px 26px;font-size:13px;font-weight:600;text-decoration:none;">
            <span style="color:#ffffff;">Acknowledge</span>
          </a>
        </td></tr>
      </table>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="x-apple-disable-message-reformatting"></head>
<body style="margin:0;padding:0;background-color:#f4f4f7;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" bgcolor="#f4f4f7" style="background-color:#f4f4f7;margin:0;padding:32px 16px;font-family:'Segoe UI',Helvetica,Arial,sans-serif;">
  <tr><td align="center">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" bgcolor="#ffffff" style="max-width:480px;background-color:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e5e5ea;">
      <tr><td style="padding:24px 28px 18px;border-bottom:1px solid #efeff4;">
        <img src="${LOGO_DATA_URI}" width="28" height="28" alt="Argus" style="display:inline-block;vertical-align:middle;border-radius:7px;" />
        <span style="display:inline-block;vertical-align:middle;margin-left:9px;font-size:15px;font-weight:700;color:#18181b;">Argus</span>
      </td></tr>
      <tr><td style="padding:24px 28px 28px;">
        <table role="presentation" cellpadding="0" cellspacing="0" style="margin-bottom:14px;">
          <tr><td bgcolor="${color}" style="background-color:${color};border-radius:9999px;padding:4px 11px;">
            <span style="color:#ffffff;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;">${escapeHtml(alert.severity)}</span>
          </td></tr>
        </table>
        <h1 style="font-size:18px;font-weight:700;color:#18181b;margin:0 0 14px;line-height:24px;">${escapeHtml(alert.title)}</h1>
        ${deviceListHtml}
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
          ${detailRows}${row("Opened", escapeHtml(alert.openedAt))}
        </table>
        <div style="margin-top:18px;">
          <a href="${deepLink}" style="font-size:13px;font-weight:600;text-decoration:none;"><span style="color:#7c3aed;">View device →</span></a>
        </div>
        ${ackButton}
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}

function row(label: string, value: string): string {
  return `<tr>
    <td style="padding:7px 0;font-size:13px;color:#71717a;width:90px;border-bottom:1px solid #f4f4f7;">${label}</td>
    <td style="padding:7px 0;font-size:13px;font-weight:600;color:#18181b;border-bottom:1px solid #f4f4f7;">${value}</td>
  </tr>`;
}

export function plainText(payload: NotifyPayload): string {
  const { alert, device, affectedDevices } = payload;
  const lines = [`[${alert.severity.toUpperCase()}] ${alert.title}`];
  if (affectedDevices && affectedDevices.length > 0) {
    lines.push(`Affected devices (${affectedDevices.length}):`);
    for (const d of affectedDevices) lines.push(`  - ${d.name} (${d.ip})`);
  } else {
    lines.push(`Device: ${device.name} (${device.ip}, ${device.type})`);
    if (alert.detail) lines.push(alert.detail);
  }
  lines.push(`Opened: ${alert.openedAt}`);
  if (payload.ackUrl) lines.push(`Acknowledge: ${payload.ackUrl}`);
  return lines.join("\n");
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}
